name: sistema_ventas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^4.0.0
  objectbox_flutter_libs: any  
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.0
  objectbox_generator: ^4.0.0

flutter:
  uses-material-design: true
